/*
* Copyright 2024 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     https://www.apache.org/licenses/LICENSE-2.0
*
*     Unless required by applicable law or agreed to in writing, software
*     distributed under the License is distributed on an "AS IS" BASIS,
*     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*     See the License for the specific language governing permissions and
*     limitations under the License.
 */

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/GoogleCloudPlatform/gke-gateway-api/apis/networking/v1"
	networkingv1 "github.com/GoogleCloudPlatform/gke-gateway-api/pkg/client/clientset/versioned/typed/networking/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeGCPSessionAffinityPolicies implements GCPSessionAffinityPolicyInterface
type fakeGCPSessionAffinityPolicies struct {
	*gentype.FakeClientWithList[*v1.GCPSessionAffinityPolicy, *v1.GCPSessionAffinityPolicyList]
	Fake *FakeNetworkingV1
}

func newFakeGCPSessionAffinityPolicies(fake *FakeNetworkingV1, namespace string) networkingv1.GCPSessionAffinityPolicyInterface {
	return &fakeGCPSessionAffinityPolicies{
		gentype.NewFakeClientWithList[*v1.GCPSessionAffinityPolicy, *v1.GCPSessionAffinityPolicyList](
			fake.Fake,
			namespace,
			v1.SchemeGroupVersion.WithResource("gcpsessionaffinitypolicies"),
			v1.SchemeGroupVersion.WithKind("GCPSessionAffinityPolicy"),
			func() *v1.GCPSessionAffinityPolicy { return &v1.GCPSessionAffinityPolicy{} },
			func() *v1.GCPSessionAffinityPolicyList { return &v1.GCPSessionAffinityPolicyList{} },
			func(dst, src *v1.GCPSessionAffinityPolicyList) { dst.ListMeta = src.ListMeta },
			func(list *v1.GCPSessionAffinityPolicyList) []*v1.GCPSessionAffinityPolicy {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1.GCPSessionAffinityPolicyList, items []*v1.GCPSessionAffinityPolicy) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
