/*
* Copyright 2024 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     https://www.apache.org/licenses/LICENSE-2.0
*
*     Unless required by applicable law or agreed to in writing, software
*     distributed under the License is distributed on an "AS IS" BASIS,
*     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*     See the License for the specific language governing permissions and
*     limitations under the License.
 */

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/GoogleCloudPlatform/gke-gateway-api/apis/networking/v1"
	networkingv1 "github.com/GoogleCloudPlatform/gke-gateway-api/pkg/client/clientset/versioned/typed/networking/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeGCPBackendPolicies implements GCPBackendPolicyInterface
type fakeGCPBackendPolicies struct {
	*gentype.FakeClientWithList[*v1.GCPBackendPolicy, *v1.GCPBackendPolicyList]
	Fake *FakeNetworkingV1
}

func newFakeGCPBackendPolicies(fake *FakeNetworkingV1, namespace string) networkingv1.GCPBackendPolicyInterface {
	return &fakeGCPBackendPolicies{
		gentype.NewFakeClientWithList[*v1.GCPBackendPolicy, *v1.GCPBackendPolicyList](
			fake.Fake,
			namespace,
			v1.SchemeGroupVersion.WithResource("gcpbackendpolicies"),
			v1.SchemeGroupVersion.WithKind("GCPBackendPolicy"),
			func() *v1.GCPBackendPolicy { return &v1.GCPBackendPolicy{} },
			func() *v1.GCPBackendPolicyList { return &v1.GCPBackendPolicyList{} },
			func(dst, src *v1.GCPBackendPolicyList) { dst.ListMeta = src.ListMeta },
			func(list *v1.GCPBackendPolicyList) []*v1.GCPBackendPolicy { return gentype.ToPointerSlice(list.Items) },
			func(list *v1.GCPBackendPolicyList, items []*v1.GCPBackendPolicy) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
