/*
* Copyright 2024 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     https://www.apache.org/licenses/LICENSE-2.0
*
*     Unless required by applicable law or agreed to in writing, software
*     distributed under the License is distributed on an "AS IS" BASIS,
*     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*     See the License for the specific language governing permissions and
*     limitations under the License.
 */

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	networkingv1 "github.com/GoogleCloudPlatform/gke-gateway-api/apis/networking/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// HealthCheckPolicyLister helps list HealthCheckPolicies.
// All objects returned here must be treated as read-only.
type HealthCheckPolicyLister interface {
	// List lists all HealthCheckPolicies in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*networkingv1.HealthCheckPolicy, err error)
	// HealthCheckPolicies returns an object that can list and get HealthCheckPolicies.
	HealthCheckPolicies(namespace string) HealthCheckPolicyNamespaceLister
	HealthCheckPolicyListerExpansion
}

// healthCheckPolicyLister implements the HealthCheckPolicyLister interface.
type healthCheckPolicyLister struct {
	listers.ResourceIndexer[*networkingv1.HealthCheckPolicy]
}

// NewHealthCheckPolicyLister returns a new HealthCheckPolicyLister.
func NewHealthCheckPolicyLister(indexer cache.Indexer) HealthCheckPolicyLister {
	return &healthCheckPolicyLister{listers.New[*networkingv1.HealthCheckPolicy](indexer, networkingv1.Resource("healthcheckpolicy"))}
}

// HealthCheckPolicies returns an object that can list and get HealthCheckPolicies.
func (s *healthCheckPolicyLister) HealthCheckPolicies(namespace string) HealthCheckPolicyNamespaceLister {
	return healthCheckPolicyNamespaceLister{listers.NewNamespaced[*networkingv1.HealthCheckPolicy](s.ResourceIndexer, namespace)}
}

// HealthCheckPolicyNamespaceLister helps list and get HealthCheckPolicies.
// All objects returned here must be treated as read-only.
type HealthCheckPolicyNamespaceLister interface {
	// List lists all HealthCheckPolicies in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*networkingv1.HealthCheckPolicy, err error)
	// Get retrieves the HealthCheckPolicy from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*networkingv1.HealthCheckPolicy, error)
	HealthCheckPolicyNamespaceListerExpansion
}

// healthCheckPolicyNamespaceLister implements the HealthCheckPolicyNamespaceLister
// interface.
type healthCheckPolicyNamespaceLister struct {
	listers.ResourceIndexer[*networkingv1.HealthCheckPolicy]
}
